H5Dcreate_vers=H5Dcreate_vers => 1
H5T_UNIX_D32BE=H5T_UNIX_D32BE => (H5OPEN H5T_UNIX_D32BE_g)
NDEBUG=NDEBUG => 1
H5_SIZEOF_SSIZE_T=H5_SIZEOF_SSIZE_T => 4
__DADDR_T_TYPE=__DADDR_T_TYPE => __S32_TYPE
NAME_MAX=NAME_MAX => 255
_POSIX2_CHARCLASS_NAME_MAX=_POSIX2_CHARCLASS_NAME_MAX => 14
H5_HAVE_FSEEKO=H5_HAVE_FSEEKO => 1
H5Dopen_vers=H5Dopen_vers => 1
__SIZEOF_PTHREAD_MUTEX_T=__SIZEOF_PTHREAD_MUTEX_T => 24
H5_HAVE_FTRUNCATE64=H5_HAVE_FTRUNCATE64 => 1
__WCHAR_MIN=__WCHAR_MIN => (-__WCHAR_MAX - 1)
SCNxLEAST64=SCNxLEAST64 => __PRI64_PREFIX "x"
H5_SIZEOF_INT64_T=H5_SIZEOF_INT64_T => 8
INT32_MIN=INT32_MIN => (-2147483647-1)
__GNUC_PREREQ=__GNUC_PREREQ(maj, min) => 0
RTSIG_MAX=RTSIG_MAX => 32
PRIdFAST8=PRIdFAST8 => "d"
H5T_INTEL_B64=H5T_INTEL_B64 => H5T_STD_B64LE
H5T_ALPHA_F32=H5T_ALPHA_F32 => H5T_IEEE_F32LE
FD_ZERO=FD_ZERO(fdsetp) => __FD_ZERO (fdsetp)
H5_HAVE_SYS_TYPES_H=H5_HAVE_SYS_TYPES_H => 1
PRIoFAST64=PRIoFAST64 => __PRI64_PREFIX "o"
__SIZEOF_PTHREAD_RWLOCKATTR_T=__SIZEOF_PTHREAD_RWLOCKATTR_T => 8
H5F_OBJ_FILE=H5F_OBJ_FILE => (0x0001u)
UINT_FAST8_MAX=UINT_FAST8_MAX => (255)
__TIME_T_TYPE=__TIME_T_TYPE => __SLONGWORD_TYPE
H5_HAVE_WAITPID=H5_HAVE_WAITPID => 1
H5_HAVE_ZLIB_H=H5_HAVE_ZLIB_H => 1
H5_SIZEOF_HADDR_T=H5_SIZEOF_HADDR_T => H5_SIZEOF_INT64_T
__SLONG32_TYPE=__SLONG32_TYPE => long int
H5Eclear=H5Eclear => H5Eclear1
__ssize_t_defined=__ssize_t_defined
makedev=makedev(maj, min) => gnu_dev_makedev (maj, min)
H5T_ALPHA_U64=H5T_ALPHA_U64 => H5T_STD_U64LE
PRIxPTR=PRIxPTR => __PRIPTR_PREFIX "x"
__SIZEOF_PTHREAD_BARRIERATTR_T=__SIZEOF_PTHREAD_BARRIERATTR_T => 4
H5T_NATIVE_LLONG=H5T_NATIVE_LLONG => (H5OPEN H5T_NATIVE_LLONG_g)
PRIoFAST32=PRIoFAST32 => __PRIPTR_PREFIX "o"
H5T_NATIVE_DOUBLE=H5T_NATIVE_DOUBLE => (H5OPEN H5T_NATIVE_DOUBLE_g)
H5T_NATIVE_INT=H5T_NATIVE_INT => (H5OPEN H5T_NATIVE_INT_g)
H5_HAVE_MEMORY_H=H5_HAVE_MEMORY_H => 1
H5_SIZEOF_INT8_T=H5_SIZEOF_INT8_T => 1
H5T_INTEL_I16=H5T_INTEL_I16 => H5T_STD_I16LE
PRIx64=PRIx64 => __PRI64_PREFIX "x"
H5T_MIPS_I8=H5T_MIPS_I8 => H5T_STD_I8BE
H5_FCDLLVAR=H5_FCDLLVAR => extern
PRIxFAST64=PRIxFAST64 => __PRI64_PREFIX "x"
H5_SIZEOF_INT_FAST8_T=H5_SIZEOF_INT_FAST8_T => 1
H5_SIZEOF_INT16_T=H5_SIZEOF_INT16_T => 2
__sigset_t_defined=__sigset_t_defined
H5_SIZEOF_UINT_LEAST16_T=H5_SIZEOF_UINT_LEAST16_T => 2
__uid_t_defined=__uid_t_defined
CHAR_MAX=CHAR_MAX => SCHAR_MAX
PRIXLEAST16=PRIXLEAST16 => "X"
H5Tarray_create=H5Tarray_create => H5Tarray_create1
SEM_VALUE_MAX=SEM_VALUE_MAX => (2147483647)
__USE_XOPEN2K8=__USE_XOPEN2K8 => 1
H5_ULLONG_TO_LDOUBLE_PRECISION=H5_ULLONG_TO_LDOUBLE_PRECISION => 1
H5T_STD_U8BE=H5T_STD_U8BE => (H5OPEN H5T_STD_U8BE_g)
__CLOCK_T_TYPE=__CLOCK_T_TYPE => __SLONGWORD_TYPE
H5T_ALPHA_F64=H5T_ALPHA_F64 => H5T_IEEE_F64LE
SCNx64=SCNx64 => __PRI64_PREFIX "x"
__SSIZE_T_TYPE=__SSIZE_T_TYPE => __SWORD_TYPE
__attribute_warn_unused_result__=__attribute_warn_unused_result__
PRIoFAST16=PRIoFAST16 => __PRIPTR_PREFIX "o"
__S32_TYPE=__S32_TYPE => int
H5_SIZEOF_INT_FAST32_T=H5_SIZEOF_INT_FAST32_T => 4
H5_ULONG_TO_FLOAT_ACCURATE=H5_ULONG_TO_FLOAT_ACCURATE => 1
FD_ISSET=FD_ISSET(fd, fdsetp) => __FD_ISSET (fd, fdsetp)
__attribute_format_strfmon__=__attribute_format_strfmon__(a, b)
H5_VERSION=H5_VERSION => "1.8.4-patch1"
EXPR_NEST_MAX=EXPR_NEST_MAX => _POSIX2_EXPR_NEST_MAX
INT_LEAST16_MIN=INT_LEAST16_MIN => (-32767-1)
H5F_ACC_RDWR=H5F_ACC_RDWR => (H5CHECK 0x0001u)
__FD_ZERO=__FD_ZERO(set) => do { unsigned int __i; fd_set *__arr = (set); for (__i = 0; __i < sizeof (fd_set) / sizeof (__fd_mask); ++__i) __FDS_BITS (__arr)[__i] = 0; } while (0)
INT8_MIN=INT8_MIN => (-128)
SCNoLEAST64=SCNoLEAST64 => __PRI64_PREFIX "o"
H5Gopen_vers=H5Gopen_vers => 1
H5_HAVE_VSNPRINTF=H5_HAVE_VSNPRINTF => 1
H5_SIZEOF_UINT_LEAST8_T=H5_SIZEOF_UINT_LEAST8_T => 1
PRIXLEAST32=PRIXLEAST32 => "X"
_POSIX_MAX_INPUT=_POSIX_MAX_INPUT => 255
H5T_STD_B32LE=H5T_STD_B32LE => (H5OPEN H5T_STD_B32LE_g)
H5T_NATIVE_B8=H5T_NATIVE_B8 => (H5OPEN H5T_NATIVE_B8_g)
H5_HAVE_RAND_R=H5_HAVE_RAND_R => 1
H5A_operator_t=H5A_operator_t => H5A_operator1_t
H5F_ACC_DEBUG=H5F_ACC_DEBUG => (H5CHECK 0x0008u)
H5_SIZEOF_UINT_FAST8_T=H5_SIZEOF_UINT_FAST8_T => 1
H5Tget_array_dims_vers=H5Tget_array_dims_vers => 1
H5_PRINTF_LL_WIDTH=H5_PRINTF_LL_WIDTH => "ll"
_BITS_PTHREADTYPES_H=_BITS_PTHREADTYPES_H => 1
SCNoLEAST32=SCNoLEAST32 => "o"
PRIXLEAST64=PRIXLEAST64 => __PRI64_PREFIX "X"
MAX_INPUT=MAX_INPUT => 255
__restrict_arr=__restrict_arr
H5_HAVE_STRING_H=H5_HAVE_STRING_H => 1
__USE_BSD=__USE_BSD => 1
INT32_C=INT32_C(c) => c
PRIdLEAST16=PRIdLEAST16 => "d"
H5_HAVE_SYS_SOCKET_H=H5_HAVE_SYS_SOCKET_H => 1
SCNdPTR=SCNdPTR => __PRIPTR_PREFIX "d"
__FDS_BITS=__FDS_BITS(set) => ((set)->__fds_bits)
__need_timespec=__need_timespec
SCNx32=SCNx32 => "x"
be64toh=be64toh(x) => __bswap_64 (x)
H5_DLL=H5_DLL
H5_SIZEOF_HID_T=H5_SIZEOF_HID_T => H5_SIZEOF_INT
H5_HAVE_ALARM=H5_HAVE_ALARM => 1
PRIoPTR=PRIoPTR => __PRIPTR_PREFIX "o"
LINE_MAX=LINE_MAX => _POSIX2_LINE_MAX
SCNxPTR=SCNxPTR => __PRIPTR_PREFIX "x"
_SYS_TYPES_H=_SYS_TYPES_H => 1
__PID_T_TYPE=__PID_T_TYPE => __S32_TYPE
PDP_ENDIAN=PDP_ENDIAN => __PDP_ENDIAN
H5_HAVE_THREADSAFE=H5_HAVE_THREADSAFE => 1
H5Tarray_create_vers=H5Tarray_create_vers => 1
PRIXFAST32=PRIXFAST32 => __PRIPTR_PREFIX "X"
INT_LEAST64_MIN=INT_LEAST64_MIN => (-__INT64_C(9223372036854775807)-1)
H5_HAVE_STAT64=H5_HAVE_STAT64 => 1
__WCHAR_MAX=__WCHAR_MAX => (2147483647)
H5_HAVE_IOCTL=H5_HAVE_IOCTL => 1
_SYS_SELECT_H=_SYS_SELECT_H => 1
_POSIX_RTSIG_MAX=_POSIX_RTSIG_MAX => 8
SCNoLEAST16=SCNoLEAST16 => "ho"
PRIdLEAST32=PRIdLEAST32 => "d"
__BIT_TYPES_DEFINED__=__BIT_TYPES_DEFINED__ => 1
LONG_MIN=LONG_MIN => (-LONG_MAX - 1L)
__blksize_t_defined=__blksize_t_defined
INTPTR_MIN=INTPTR_MIN => (-2147483647-1)
__U32_TYPE=__U32_TYPE => unsigned int
SCNuLEAST64=SCNuLEAST64 => __PRI64_PREFIX "u"
H5_HAVE_INTTYPES_H=H5_HAVE_INTTYPES_H => 1
__extern_inline=__extern_inline => extern __inline
ULONG_MAX=ULONG_MAX => 4294967295UL
H5_HAVE_GETTIMEOFDAY=H5_HAVE_GETTIMEOFDAY => 1
be32toh=be32toh(x) => __bswap_32 (x)
H5Aiterate=H5Aiterate => H5Aiterate1
H5Pget_filter_by_id=H5Pget_filter_by_id => H5Pget_filter_by_id1
PRId8=PRId8 => "d"
H5AC__CURR_CACHE_CONFIG_VERSION=H5AC__CURR_CACHE_CONFIG_VERSION => 1
H5T_STD_REF_DSETREG=H5T_STD_REF_DSETREG => (H5OPEN H5T_STD_REF_DSETREG_g)
_BSD_SOURCE=_BSD_SOURCE => 1
H5_HAVE_FILTER_SHUFFLE=H5_HAVE_FILTER_SHUFFLE => 1
__bos0=__bos0(ptr) => __builtin_object_size (ptr, 0)
__USE_POSIX=__USE_POSIX => 1
H5_HAVE_STDINT_H=H5_HAVE_STDINT_H => 1
__LDBL_REDIR=__LDBL_REDIR(name, proto) => name proto
H5_FP_TO_INTEGER_OVERFLOW_WORKS=H5_FP_TO_INTEGER_OVERFLOW_WORKS => 1
SCNiFAST16=SCNiFAST16 => __PRIPTR_PREFIX "i"
__timer_t_defined=__timer_t_defined => 1
__USE_SVID=__USE_SVID => 1
TTY_NAME_MAX=TTY_NAME_MAX => 32
__LITTLE_ENDIAN=__LITTLE_ENDIAN => 1234
__USE_ISOC99=__USE_ISOC99 => 1
H5_HAVE_LSEEK64=H5_HAVE_LSEEK64 => 1
SIG_ATOMIC_MIN=SIG_ATOMIC_MIN => (-2147483647-1)
H5F_OBJ_ATTR=H5F_OBJ_ATTR => (0x0010u)
__USE_ISOC95=__USE_ISOC95 => 1
SCNiMAX=SCNiMAX => __PRI64_PREFIX "i"
LITTLE_ENDIAN=LITTLE_ENDIAN => __LITTLE_ENDIAN
_POSIX_TTY_NAME_MAX=_POSIX_TTY_NAME_MAX => 9
_WIN32=_WIN32 => 1
H5F_OBJ_ALL=H5F_OBJ_ALL => (H5F_OBJ_FILE|H5F_OBJ_DATASET|H5F_OBJ_GROUP|H5F_OBJ_DATATYPE|H5F_OBJ_ATTR)
BIG_ENDIAN=BIG_ENDIAN => __BIG_ENDIAN
H5T_NATIVE_UINT=H5T_NATIVE_UINT => (H5OPEN H5T_NATIVE_UINT_g)
_H5public_H=_H5public_H
CHAR_MIN=CHAR_MIN => SCHAR_MIN
H5T_NATIVE_SCHAR=H5T_NATIVE_SCHAR => (H5OPEN H5T_NATIVE_SCHAR_g)
__UWORD_TYPE=__UWORD_TYPE => unsigned int
_POSIX_MQ_OPEN_MAX=_POSIX_MQ_OPEN_MAX => 8
PRIdLEAST64=PRIdLEAST64 => __PRI64_PREFIX "d"
_POSIX_THREAD_DESTRUCTOR_ITERATIONS=_POSIX_THREAD_DESTRUCTOR_ITERATIONS => 4
H5_DEV_T_IS_SCALAR=H5_DEV_T_IS_SCALAR => 1
H5T_NATIVE_INT8=H5T_NATIVE_INT8 => (H5OPEN H5T_NATIVE_INT8_g)
PRIXMAX=PRIXMAX => __PRI64_PREFIX "X"
SCNdLEAST16=SCNdLEAST16 => "hd"
H5T_NATIVE_HSSIZE=H5T_NATIVE_HSSIZE => (H5OPEN H5T_NATIVE_HSSIZE_g)
SCNuLEAST16=SCNuLEAST16 => "hu"
INT_FAST32_MIN=INT_FAST32_MIN => (-2147483647-1)
__USECONDS_T_TYPE=__USECONDS_T_TYPE => __U32_TYPE
_POSIX_TZNAME_MAX=_POSIX_TZNAME_MAX => 6
SCNiFAST32=SCNiFAST32 => __PRIPTR_PREFIX "i"
INT_FAST16_MIN=INT_FAST16_MIN => (-2147483647-1)
PRIuFAST64=PRIuFAST64 => __PRI64_PREFIX "u"
FD_SETSIZE=FD_SETSIZE => __FD_SETSIZE
__BLKCNT_T_TYPE=__BLKCNT_T_TYPE => __SLONGWORD_TYPE
PRIiMAX=PRIiMAX => __PRI64_PREFIX "i"
H5T_NATIVE_LDOUBLE=H5T_NATIVE_LDOUBLE => (H5OPEN H5T_NATIVE_LDOUBLE_g)
H5_SIZEOF_UINT_FAST64_T=H5_SIZEOF_UINT_FAST64_T => 8
FD_CLR=FD_CLR(fd, fdsetp) => __FD_CLR (fd, fdsetp)
PRIoMAX=PRIoMAX => __PRI64_PREFIX "o"
__SQUAD_TYPE=__SQUAD_TYPE => __quad_t
__clockid_t_defined=__clockid_t_defined => 1
PRIi8=PRIi8 => "i"
PRIuLEAST32=PRIuLEAST32 => "u"
UINTMAX_MAX=UINTMAX_MAX => (__UINT64_C(18446744073709551615))
H5T_NATIVE_INT_LEAST64=H5T_NATIVE_INT_LEAST64 => (H5OPEN H5T_NATIVE_INT_LEAST64_g)
H5T_MIPS_B8=H5T_MIPS_B8 => H5T_STD_B8BE
__FSFILCNT64_T_TYPE=__FSFILCNT64_T_TYPE => __UQUAD_TYPE
H5F_OBJ_DATATYPE=H5F_OBJ_DATATYPE => (0x0008u)
__unbounded=__unbounded
SCNxLEAST32=SCNxLEAST32 => "x"
H5_PACKAGE_BUGREPORT=H5_PACKAGE_BUGREPORT => "help@hdfgroup.org"
__FDELT=__FDELT(d) => ((d) / __NFDBITS)
__FSFILCNT_T_TYPE=__FSFILCNT_T_TYPE => __ULONGWORD_TYPE
INT64_C=INT64_C(c) => c ## LL
SCNdLEAST32=SCNdLEAST32 => "d"
_BITS_TYPESIZES_H=_BITS_TYPESIZES_H => 1
H5_HAVE_SNPRINTF=H5_HAVE_SNPRINTF => 1
PRIx16=PRIx16 => "x"
SCNuLEAST32=SCNuLEAST32 => "u"
__GID_T_TYPE=__GID_T_TYPE => __U32_TYPE
__fsblkcnt_t_defined=__fsblkcnt_t_defined
PRIXFAST16=PRIXFAST16 => __PRIPTR_PREFIX "X"
LONG_MAX=LONG_MAX => 2147483647L
H5T_MIPS_F64=H5T_MIPS_F64 => H5T_IEEE_F64BE
INT8_MAX=INT8_MAX => (127)
H5_SIZEOF_UINT_LEAST64_T=H5_SIZEOF_UINT_LEAST64_T => 8
H5T_NATIVE_INT_LEAST32=H5T_NATIVE_INT_LEAST32 => (H5OPEN H5T_NATIVE_INT_LEAST32_g)
_POSIX_THREAD_KEYS_MAX=_POSIX_THREAD_KEYS_MAX => 128
H5T_MIPS_U16=H5T_MIPS_U16 => H5T_STD_U16BE
__PDP_ENDIAN=__PDP_ENDIAN => 3412
__ULONG32_TYPE=__ULONG32_TYPE => unsigned long int
H5T_STD_I64LE=H5T_STD_I64LE => (H5OPEN H5T_STD_I64LE_g)
SCNdLEAST8=SCNdLEAST8 => "hhd"
_POSIX2_LINE_MAX=_POSIX2_LINE_MAX => 2048
_INTTYPES_H=_INTTYPES_H => 1
PRIuLEAST16=PRIuLEAST16 => "u"
SCNdLEAST64=SCNdLEAST64 => __PRI64_PREFIX "d"
major=major(dev) => gnu_dev_major (dev)
SCNuMAX=SCNuMAX => __PRI64_PREFIX "u"
H5T_NATIVE_SHORT=H5T_NATIVE_SHORT => (H5OPEN H5T_NATIVE_SHORT_g)
__LINE__=__LINE__
__bounded=__bounded
PRIuFAST32=PRIuFAST32 => __PRIPTR_PREFIX "u"
_POSIX_AIO_LISTIO_MAX=_POSIX_AIO_LISTIO_MAX => 2
H5T_IEEE_F64LE=H5T_IEEE_F64LE => (H5OPEN H5T_IEEE_F64LE_g)
_H5PTpublic_H=_H5PTpublic_H
SCNxLEAST16=SCNxLEAST16 => "hx"
H5_CXX_HAVE_OFFSETOF=H5_CXX_HAVE_OFFSETOF => 1
H5E_walk_t=H5E_walk_t => H5E_walk1_t
PRIx32=PRIx32 => "x"
H5Pregister_vers=H5Pregister_vers => 1
SCNoFAST64=SCNoFAST64 => __PRI64_PREFIX "o"
__LDBL_REDIR1_NTH=__LDBL_REDIR1_NTH(name, proto, alias) => name proto __THROW
H5_SIZEOF_UINT_LEAST32_T=H5_SIZEOF_UINT_LEAST32_T => 4
SCNo64=SCNo64 => __PRI64_PREFIX "o"
XATTR_SIZE_MAX=XATTR_SIZE_MAX => 65536
H5T_FORTRAN_S1=H5T_FORTRAN_S1 => (H5OPEN H5T_FORTRAN_S1_g)
H5_SIZEOF_UINT8_T=H5_SIZEOF_UINT8_T => 1
H5Rget_obj_type=H5Rget_obj_type => H5Rget_obj_type1
_POSIX_CLOCKRES_MIN=_POSIX_CLOCKRES_MIN => 20000000
_SIGSET_NWORDS=_SIGSET_NWORDS => (1024 / (8 * sizeof (unsigned long int)))
INT8_C=INT8_C(c) => c
H5_HAVE_SYS_STAT_H=H5_HAVE_SYS_STAT_H => 1
H5_HAVE_GETRUSAGE=H5_HAVE_GETRUSAGE => 1
H5T_IEEE_F32LE=H5T_IEEE_F32LE => (H5OPEN H5T_IEEE_F32LE_g)
__PMT=__PMT(args) => args
H5_HAVE_STRUCT_TM_TM_ZONE=H5_HAVE_STRUCT_TM_TM_ZONE => 1
INT16_MIN=INT16_MIN => (-32767-1)
H5F_ACC_RDONLY=H5F_ACC_RDONLY => (H5CHECK 0x0000u)
H5T_STD_I16LE=H5T_STD_I16LE => (H5OPEN H5T_STD_I16LE_g)
_ENDIAN_H=_ENDIAN_H => 1
__U16_TYPE=__U16_TYPE => unsigned short int
H5T_NATIVE_UINT32=H5T_NATIVE_UINT32 => (H5OPEN H5T_NATIVE_UINT32_g)
H5T_MIPS_U32=H5T_MIPS_U32 => H5T_STD_U32BE
FD_SET=FD_SET(fd, fdsetp) => __FD_SET (fd, fdsetp)
INTPTR_MAX=INTPTR_MAX => (2147483647)
H5Gcreate=H5Gcreate => H5Gcreate1
__SIZEOF_PTHREAD_COND_T=__SIZEOF_PTHREAD_COND_T => 48
__bswap_16=__bswap_16(x) => (__extension__ ({ register unsigned short int __x = (unsigned short int) (x); __bswap_constant_16 (__x); }))
H5_HAVE_TM_GMTOFF=H5_HAVE_TM_GMTOFF => 1
__SIZEOF_PTHREAD_ATTR_T=__SIZEOF_PTHREAD_ATTR_T => 36
H5T_ALPHA_B32=H5T_ALPHA_B32 => H5T_STD_B32LE
XATTR_NAME_MAX=XATTR_NAME_MAX => 255
H5Epush_vers=H5Epush_vers => 1
H5_PRINTF_HADDR_FMT=H5_PRINTF_HADDR_FMT => "%"H5_PRINTF_LL_WIDTH"u"
_POSIX_MAX_CANON=_POSIX_MAX_CANON => 255
H5T_INTEL_F64=H5T_INTEL_F64 => H5T_IEEE_F64LE
BC_DIM_MAX=BC_DIM_MAX => _POSIX2_BC_DIM_MAX
H5_HAVE_C99_FUNC=H5_HAVE_C99_FUNC => 1
PRIuMAX=PRIuMAX => __PRI64_PREFIX "u"
INT_LEAST8_MAX=INT_LEAST8_MAX => (127)
H5T_MIPS_U64=H5T_MIPS_U64 => H5T_STD_U64BE
__flexarr=__flexarr => [0]
SCNdMAX=SCNdMAX => __PRI64_PREFIX "d"
PRIi16=PRIi16 => "i"
H5_SIZEOF___INT64=H5_SIZEOF___INT64 => 0
H5_HAVE_VASPRINTF=H5_HAVE_VASPRINTF => 1
H5T_NATIVE_HERR=H5T_NATIVE_HERR => (H5OPEN H5T_NATIVE_HERR_g)
H5T_MIPS_F32=H5T_MIPS_F32 => H5T_IEEE_F32BE
H5Acreate=H5Acreate => H5Acreate1
H5E_auto_t_vers=H5E_auto_t_vers => 1
__WORDSIZE=__WORDSIZE => 32
__fsfilcnt_t_defined=__fsfilcnt_t_defined
PRIo8=PRIo8 => "o"
__USE_POSIX2=__USE_POSIX2 => 1
UINT8_MAX=UINT8_MAX => (255)
_POSIX_SYMLINK_MAX=_POSIX_SYMLINK_MAX => 255
H5T_STD_I8LE=H5T_STD_I8LE => (H5OPEN H5T_STD_I8LE_g)
__bswap_32=__bswap_32(x) => (__extension__ ({ register unsigned int __x = (x); __bswap_constant_32 (__x); }))
__PRIPTR_PREFIX=__PRIPTR_PREFIX
H5T_ALPHA_B16=H5T_ALPHA_B16 => H5T_STD_B16LE
H5T_NCSET=H5T_NCSET => H5T_CSET_RESERVED_2
SIG_ATOMIC_MAX=SIG_ATOMIC_MAX => (2147483647)
H5T_NATIVE_UINT64=H5T_NATIVE_UINT64 => (H5OPEN H5T_NATIVE_UINT64_g)
HADDR_UNDEF=HADDR_UNDEF => ((haddr_t)(int64_t)(-1))
PRIi32=PRIi32 => "i"
_H5Ipublic_H=_H5Ipublic_H
_POSIX_DELAYTIMER_MAX=_POSIX_DELAYTIMER_MAX => 32
UINT_FAST64_MAX=UINT_FAST64_MAX => (__UINT64_C(18446744073709551615))
PRIXFAST64=PRIXFAST64 => __PRI64_PREFIX "X"
_BITS_WCHAR_H=_BITS_WCHAR_H => 1
PTRDIFF_MAX=PTRDIFF_MAX => (2147483647)
SCNd16=SCNd16 => "hd"
__attribute_used__=__attribute_used__ => __attribute__ ((__unused__))
H5T_ALPHA_B64=H5T_ALPHA_B64 => H5T_STD_B64LE
SCNi16=SCNi16 => "hi"
INT_FAST32_MAX=INT_FAST32_MAX => (2147483647)
H5F_UNLIMITED=H5F_UNLIMITED => ((hsize_t)(-1L))
__warndecl=__warndecl(name, msg) => extern void name (void)
INT_FAST16_MAX=INT_FAST16_MAX => (2147483647)
__wur=__wur
SCNoFAST32=SCNoFAST32 => __PRIPTR_PREFIX "o"
__SIZEOF_PTHREAD_RWLOCK_T=__SIZEOF_PTHREAD_RWLOCK_T => 32
SCNuFAST64=SCNuFAST64 => __PRI64_PREFIX "u"
SCNo16=SCNo16 => "ho"
__dev_t_defined=__dev_t_defined
_POSIX_HOST_NAME_MAX=_POSIX_HOST_NAME_MAX => 255
H5_SIZEOF_CHAR=H5_SIZEOF_CHAR => 1
__PRI64_PREFIX=__PRI64_PREFIX => "ll"
PRIdLEAST8=PRIdLEAST8 => "d"
SCNi32=SCNi32 => "i"
H5_HAVE_PTHREAD_H=H5_HAVE_PTHREAD_H => 1
__USE_POSIX_IMPLICITLY=__USE_POSIX_IMPLICITLY => 1
__BLKCNT64_T_TYPE=__BLKCNT64_T_TYPE => __SQUAD_TYPE
INT_LEAST32_MIN=INT_LEAST32_MIN => (-2147483647-1)
H5T_NATIVE_ULLONG=H5T_NATIVE_ULLONG => (H5OPEN H5T_NATIVE_ULLONG_g)
__LDBL_REDIR_NTH=__LDBL_REDIR_NTH(name, proto) => name proto __THROW
le64toh=le64toh(x) => (x)
__SIZEOF_PTHREAD_MUTEXATTR_T=__SIZEOF_PTHREAD_MUTEXATTR_T => 4
__ptr_t=__ptr_t => void *
H5_HAVE_FILTER_FLETCHER32=H5_HAVE_FILTER_FLETCHER32 => 1
_POSIX_TIMER_MAX=_POSIX_TIMER_MAX => 32
H5T_ALPHA_U8=H5T_ALPHA_U8 => H5T_STD_U8LE
H5T_UNIX_D32LE=H5T_UNIX_D32LE => (H5OPEN H5T_UNIX_D32LE_g)
__USE_MISC=__USE_MISC => 1
__attribute__=__attribute__(xyz)
H5T_STD_REF_OBJ=H5T_STD_REF_OBJ => (H5OPEN H5T_STD_REF_OBJ_g)
H5_HAVE_FILTER_DEFLATE=H5_HAVE_FILTER_DEFLATE => 1
__SIZEOF_PTHREAD_BARRIER_T=__SIZEOF_PTHREAD_BARRIER_T => 20
H5CHECK=H5CHECK => H5check(),
__USE_ANSI=__USE_ANSI => 1
__COUNTER__=__COUNTER__
__INO_T_TYPE=__INO_T_TYPE => __ULONGWORD_TYPE
_POSIX_NGROUPS_MAX=_POSIX_NGROUPS_MAX => 8
__END_NAMESPACE_C99=__END_NAMESPACE_C99
PTHREAD_DESTRUCTOR_ITERATIONS=PTHREAD_DESTRUCTOR_ITERATIONS => _POSIX_THREAD_DESTRUCTOR_ITERATIONS
SCNo32=SCNo32 => "o"
UINT_LEAST64_MAX=UINT_LEAST64_MAX => (__UINT64_C(18446744073709551615))
_H5Tpublic_H=_H5Tpublic_H
__UID_T_TYPE=__UID_T_TYPE => __U32_TYPE
H5Z_class_t_vers=H5Z_class_t_vers => 1
SCNuFAST32=SCNuFAST32 => __PRIPTR_PREFIX "u"
__attribute_format_arg__=__attribute_format_arg__(x)
H5_PACKAGE_NAME=H5_PACKAGE_NAME => "HDF5"
_POSIX_PIPE_BUF=_POSIX_PIPE_BUF => 512
H5_HAVE_TM_ZONE=H5_HAVE_TM_ZONE => 1
__clock_t_defined=__clock_t_defined => 1
__USING_NAMESPACE_STD=__USING_NAMESPACE_STD(name)
H5_LDOUBLE_TO_UINT_ACCURATE=H5_LDOUBLE_TO_UINT_ACCURATE => 1
H5_INTEGER_TO_LDOUBLE_ACCURATE=H5_INTEGER_TO_LDOUBLE_ACCURATE => 1
H5_SIZEOF_INT=H5_SIZEOF_INT => 4
SCNd64=SCNd64 => __PRI64_PREFIX "d"
_POSIX_OPEN_MAX=_POSIX_OPEN_MAX => 20
INT16_MAX=INT16_MAX => (32767)
H5T_STD_U64BE=H5T_STD_U64BE => (H5OPEN H5T_STD_U64BE_g)
H5T_STD_I64BE=H5T_STD_I64BE => (H5OPEN H5T_STD_I64BE_g)
PRIu8=PRIu8 => "u"
H5T_NATIVE_B32=H5T_NATIVE_B32 => (H5OPEN H5T_NATIVE_B32_g)
SCNiLEAST32=SCNiLEAST32 => "i"
H5_HAVE_EMBEDDED_LIBINFO=H5_HAVE_EMBEDDED_LIBINFO => 1
PRIi64=PRIi64 => __PRI64_PREFIX "i"
H5F_OBJ_GROUP=H5F_OBJ_GROUP => (0x0004u)
H5_SIZEOF_SHORT=H5_SIZEOF_SHORT => 2
SCNd32=SCNd32 => "d"
SCNiLEAST16=SCNiLEAST16 => "hi"
H5T_NATIVE_UINT_LEAST64=H5T_NATIVE_UINT_LEAST64 => (H5OPEN H5T_NATIVE_UINT_LEAST64_g)
UINT_FAST16_MAX=UINT_FAST16_MAX => (4294967295U)
UINT32_C=UINT32_C(c) => c ## U
_POSIX_LOGIN_NAME_MAX=_POSIX_LOGIN_NAME_MAX => 9
__SLONGWORD_TYPE=__SLONGWORD_TYPE => long int
H5_SIZEOF_INT_LEAST64_T=H5_SIZEOF_INT_LEAST64_T => 8
H5T_STD_I8BE=H5T_STD_I8BE => (H5OPEN H5T_STD_I8BE_g)
H5_LLONG_TO_LDOUBLE_CORRECT=H5_LLONG_TO_LDOUBLE_CORRECT => 1
__CLOCKID_T_TYPE=__CLOCKID_T_TYPE => __S32_TYPE
__need_wchar_t=__need_wchar_t
__UINT64_C=__UINT64_C(c) => c ## ULL
H5_PACKAGE=H5_PACKAGE => "hdf5"
SCNoFAST16=SCNoFAST16 => __PRIPTR_PREFIX "o"
_POSIX_SOURCE=_POSIX_SOURCE => 1
SCNxMAX=SCNxMAX => __PRI64_PREFIX "x"
H5_HAVE_SYS_IOCTL_H=H5_HAVE_SYS_IOCTL_H => 1
_H5Cpublic_H=_H5Cpublic_H
H5_FP_TO_ULLONG_ACCURATE=H5_FP_TO_ULLONG_ACCURATE => 1
_POSIX_RE_DUP_MAX=_POSIX_RE_DUP_MAX => 255
__THROW=__THROW
H5T_NATIVE_UINT_FAST8=H5T_NATIVE_UINT_FAST8 => (H5OPEN H5T_NATIVE_UINT_FAST8_g)
H5T_STD_B8BE=H5T_STD_B8BE => (H5OPEN H5T_STD_B8BE_g)
PRIoLEAST16=PRIoLEAST16 => "o"
__U64_TYPE=__U64_TYPE => __u_quad_t
PTRDIFF_MIN=PTRDIFF_MIN => (-2147483647-1)
H5T_NATIVE_B64=H5T_NATIVE_B64 => (H5OPEN H5T_NATIVE_B64_g)
PTHREAD_KEYS_MAX=PTHREAD_KEYS_MAX => 1024
H5F_FAMILY_DEFAULT=H5F_FAMILY_DEFAULT => (hsize_t)0
PRIx8=PRIx8 => "x"
H5T_INTEL_B16=H5T_INTEL_B16 => H5T_STD_B16LE
_POSIX_ARG_MAX=_POSIX_ARG_MAX => 4096
UINT32_MAX=UINT32_MAX => (4294967295U)
H5Pregister=H5Pregister => H5Pregister1
H5_SIZEOF_OFF_T=H5_SIZEOF_OFF_T => 8
H5_SIZEOF_SIZE_T=H5_SIZEOF_SIZE_T => 4
__STDC_IEC_559_COMPLEX__=__STDC_IEC_559_COMPLEX__ => 1
H5T_NATIVE_HBOOL=H5T_NATIVE_HBOOL => (H5OPEN H5T_NATIVE_HBOOL_g)
INT_LEAST8_MIN=INT_LEAST8_MIN => (-128)
H5_HAVE_STAT_ST_BLOCKS=H5_HAVE_STAT_ST_BLOCKS => 1
TARGET_CPU_X86=TARGET_CPU_X86 => 1
__always_inline=__always_inline => __inline
H5T_NATIVE_ULONG=H5T_NATIVE_ULONG => (H5OPEN H5T_NATIVE_ULONG_g)
__blkcnt_t_defined=__blkcnt_t_defined
UCHAR_MAX=UCHAR_MAX => 255
__cleanup_fct_attribute=__cleanup_fct_attribute => __attribute__ ((__regparm__ (1)))
PRIoLEAST32=PRIoLEAST32 => "o"
H5T_NATIVE_UINT_LEAST16=H5T_NATIVE_UINT_LEAST16 => (H5OPEN H5T_NATIVE_UINT_LEAST16_g)
H5_SIZEOF_HSIZE_T=H5_SIZEOF_HSIZE_T => H5_SIZEOF_LONG_LONG
PRIxFAST32=PRIxFAST32 => __PRIPTR_PREFIX "x"
H5T_NSTR=H5T_NSTR => H5T_STR_RESERVED_3
__long_double_t=__long_double_t => long double
H5_TIME_WITH_SYS_TIME=H5_TIME_WITH_SYS_TIME => 1
H5P_DEFAULT=H5P_DEFAULT => 0
H5API_ADPT_H=H5API_ADPT_H
SCNuFAST16=SCNuFAST16 => __PRIPTR_PREFIX "u"
H5T_INTEL_B32=H5T_INTEL_B32 => H5T_STD_B32LE
INT_LEAST32_MAX=INT_LEAST32_MAX => (2147483647)
H5_HAVE_SYS_TIME_H=H5_HAVE_SYS_TIME_H => 1
__NTH=__NTH(fct) => fct
H5T_NATIVE_UINT8=H5T_NATIVE_UINT8 => (H5OPEN H5T_NATIVE_UINT8_g)
MAX_CANON=MAX_CANON => 255
H5E_auto_t=H5E_auto_t => H5E_auto1_t
H5T_ALPHA_U32=H5T_ALPHA_U32 => H5T_STD_U32LE
_ATFILE_SOURCE=_ATFILE_SOURCE => 1
H5Eset_auto=H5Eset_auto => H5Eset_auto1
H5_SIZEOF_LONG_DOUBLE=H5_SIZEOF_LONG_DOUBLE => 12
H5Eget_auto=H5Eget_auto => H5Eget_auto1
BC_BASE_MAX=BC_BASE_MAX => _POSIX2_BC_BASE_MAX
_POSIX_THREAD_THREADS_MAX=_POSIX_THREAD_THREADS_MAX => 64
__intptr_t_defined=__intptr_t_defined
H5Rget_obj_type_vers=H5Rget_obj_type_vers => 1
_POSIX_AIO_MAX=_POSIX_AIO_MAX => 1
H5_VERS_RELEASE=H5_VERS_RELEASE => 4
H5T_ALPHA_U16=H5T_ALPHA_U16 => H5T_STD_U16LE
PRIxFAST16=PRIxFAST16 => __PRIPTR_PREFIX "x"
H5_SIZEOF_OFF64_T=H5_SIZEOF_OFF64_T => 8
PRIoLEAST64=PRIoLEAST64 => __PRI64_PREFIX "o"
H5T_NATIVE_UINT16=H5T_NATIVE_UINT16 => (H5OPEN H5T_NATIVE_UINT16_g)
H5F_ACC_EXCL=H5F_ACC_EXCL => (H5CHECK 0x0004u)
H5T_C_S1=H5T_C_S1 => (H5OPEN H5T_C_S1_g)
__ID_T_TYPE=__ID_T_TYPE => __U32_TYPE
H5TEST_DLL=H5TEST_DLL
H5T_NATIVE_UINT_LEAST32=H5T_NATIVE_UINT_LEAST32 => (H5OPEN H5T_NATIVE_UINT_LEAST32_g)
H5T_STD_I16BE=H5T_STD_I16BE => (H5OPEN H5T_STD_I16BE_g)
H5T_INTEL_F32=H5T_INTEL_F32 => H5T_IEEE_F32LE
H5T_MIPS_U8=H5T_MIPS_U8 => H5T_STD_U8BE
__off_t_defined=__off_t_defined
H5T_STD_U64LE=H5T_STD_U64LE => (H5OPEN H5T_STD_U64LE_g)
SCNiFAST8=SCNiFAST8 => "hhi"
H5Pget_filter=H5Pget_filter => H5Pget_filter1
PRIdFAST32=PRIdFAST32 => __PRIPTR_PREFIX "d"
H5_HAVE_STRINGS_H=H5_HAVE_STRINGS_H => 1
PRIiFAST64=PRIiFAST64 => __PRI64_PREFIX "i"
H5T_STD_U16LE=H5T_STD_U16LE => (H5OPEN H5T_STD_U16LE_g)
H5T_STD_B16BE=H5T_STD_B16BE => (H5OPEN H5T_STD_B16BE_g)
H5Tcommit=H5Tcommit => H5Tcommit1
H5Eprint_vers=H5Eprint_vers => 1
__attribute_malloc__=__attribute_malloc__
H5_DLLVAR=H5_DLLVAR => extern
__GLIBC_HAVE_LONG_LONG=__GLIBC_HAVE_LONG_LONG => 1
__attribute_pure__=__attribute_pure__
H5T_NATIVE_INT_LEAST8=H5T_NATIVE_INT_LEAST8 => (H5OPEN H5T_NATIVE_INT_LEAST8_g)
H5_PACKAGE_STRING=H5_PACKAGE_STRING => "HDF5 1.8.4-patch1"
H5_VERS_MAJOR=H5_VERS_MAJOR => 1
SCNdFAST16=SCNdFAST16 => __PRIPTR_PREFIX "d"
H5T_UNIX_D64BE=H5T_UNIX_D64BE => (H5OPEN H5T_UNIX_D64BE_g)
H5_HLCPPDLL=H5_HLCPPDLL
INTMAX_MIN=INTMAX_MIN => (-__INT64_C(9223372036854775807)-1)
__BYTE_ORDER=__BYTE_ORDER => __LITTLE_ENDIAN
SCHAR_MAX=SCHAR_MAX => 127
__INO64_T_TYPE=__INO64_T_TYPE => __UQUAD_TYPE
_LINUX_LIMITS_H=_LINUX_LIMITS_H
SCNiLEAST64=SCNiLEAST64 => __PRI64_PREFIX "i"
__suseconds_t_defined=__suseconds_t_defined
__BLKSIZE_T_TYPE=__BLKSIZE_T_TYPE => __SLONGWORD_TYPE
PRIxLEAST8=PRIxLEAST8 => "x"
H5_ULONG_TO_FP_BOTTOM_BIT_ACCURATE=H5_ULONG_TO_FP_BOTTOM_BIT_ACCURATE => 1
H5T_NATIVE_INT64=H5T_NATIVE_INT64 => (H5OPEN H5T_NATIVE_INT64_g)
H5_HAVE_C99_DESIGNATED_INITIALIZER=H5_HAVE_C99_DESIGNATED_INITIALIZER => 1
be16toh=be16toh(x) => __bswap_16 (x)
H5_HAVE_FUNCTION=H5_HAVE_FUNCTION => 1
H5_VERS_INFO=H5_VERS_INFO => "HDF5 library version: 1.8.4-patch1"
_POSIX2_COLL_WEIGHTS_MAX=_POSIX2_COLL_WEIGHTS_MAX => 2
H5_SIZEOF_LONG_LONG=H5_SIZEOF_LONG_LONG => 8
H5_STDC_HEADERS=H5_STDC_HEADERS => 1
H5_DEFAULT_VFD=H5_DEFAULT_VFD => H5FD_SEC2
PRIuPTR=PRIuPTR => __PRIPTR_PREFIX "u"
H5T_STD_B8LE=H5T_STD_B8LE => (H5OPEN H5T_STD_B8LE_g)
SCNdFAST32=SCNdFAST32 => __PRIPTR_PREFIX "d"
HOFFSET=HOFFSET(S, M) => (offsetof(S,M))
__time_t_defined=__time_t_defined => 1
AIO_PRIO_DELTA_MAX=AIO_PRIO_DELTA_MAX => 20
SCNdFAST8=SCNdFAST8 => "hhd"
UINTPTR_MAX=UINTPTR_MAX => (4294967295U)
__STDC_IEC_559__=__STDC_IEC_559__ => 1
H5_ITER_STOP=H5_ITER_STOP => (1)
PRIuLEAST8=PRIuLEAST8 => "u"
H5T_NATIVE_UINT_FAST64=H5T_NATIVE_UINT_FAST64 => (H5OPEN H5T_NATIVE_UINT_FAST64_g)
PRIXFAST8=PRIXFAST8 => "X"
H5T_ALPHA_B8=H5T_ALPHA_B8 => H5T_STD_B8LE
__FDMASK=__FDMASK(d) => ((__fd_mask) 1 << ((d) % __NFDBITS))
__extension__=__extension__
PRIo16=PRIo16 => "o"
__GLIBC__=__GLIBC__ => 2
__USE_FORTIFY_LEVEL=__USE_FORTIFY_LEVEL => 0
H5Ewalk_vers=H5Ewalk_vers => 1
H5_GETTIMEOFDAY_GIVES_TZ=H5_GETTIMEOFDAY_GIVES_TZ => 1
H5T_NATIVE_UINT_FAST32=H5T_NATIVE_UINT_FAST32 => (H5OPEN H5T_NATIVE_UINT_FAST32_g)
__warnattr=__warnattr(msg)
H5_HAVE_UNISTD_H=H5_HAVE_UNISTD_H => 1
H5_HAVE_FORK=H5_HAVE_FORK => 1
H5Topen=H5Topen => H5Topen1
H5T_ALPHA_I8=H5T_ALPHA_I8 => H5T_STD_I8LE
PTHREAD_STACK_MIN=PTHREAD_STACK_MIN => 16384
H5T_NATIVE_INT32=H5T_NATIVE_INT32 => (H5OPEN H5T_NATIVE_INT32_g)
__INT64_C=__INT64_C(c) => c ## LL
UINT16_MAX=UINT16_MAX => (65535)
H5T_NATIVE_B16=H5T_NATIVE_B16 => (H5OPEN H5T_NATIVE_B16_g)
ULLONG_MAX=ULLONG_MAX => 18446744073709551615ULL
_STDINT_H=_STDINT_H => 1
__GNUC__=__GNUC__ => 1
SCNx16=SCNx16 => "hx"
_POSIX_SYMLOOP_MAX=_POSIX_SYMLOOP_MAX => 8
_POSIX2_EXPR_NEST_MAX=_POSIX2_EXPR_NEST_MAX => 32
H5T_NATIVE_INT16=H5T_NATIVE_INT16 => (H5OPEN H5T_NATIVE_INT16_g)
H5Tget_array_dims=H5Tget_array_dims => H5Tget_array_dims1
H5F_OBJ_DATASET=H5F_OBJ_DATASET => (0x0002u)
H5_SIZEOF_INT_LEAST16_T=H5_SIZEOF_INT_LEAST16_T => 2
UINT_LEAST16_MAX=UINT_LEAST16_MAX => (65535)
UINT8_C=UINT8_C(c) => c
__USE_POSIX199309=__USE_POSIX199309 => 1
SCNxFAST8=SCNxFAST8 => "hhx"
__GLIBC_PREREQ=__GLIBC_PREREQ(maj, min) => ((__GLIBC__ << 16) + __GLIBC_MINOR__ >= ((maj) << 16) + (min))
UINT64_MAX=UINT64_MAX => (__UINT64_C(18446744073709551615))
H5T_NATIVE_INT_FAST16=H5T_NATIVE_INT_FAST16 => (H5OPEN H5T_NATIVE_INT_FAST16_g)
NGROUPS_MAX=NGROUPS_MAX => 65536
PRIdFAST16=PRIdFAST16 => __PRIPTR_PREFIX "d"
H5_HAVE_FILTER_NBIT=H5_HAVE_FILTER_NBIT => 1
H5T_STD_B64LE=H5T_STD_B64LE => (H5OPEN H5T_STD_B64LE_g)
H5_HAVE_LIBZ=H5_HAVE_LIBZ => 1
INTMAX_C=INTMAX_C(c) => c ## LL
H5T_NATIVE_UINT_FAST16=H5T_NATIVE_UINT_FAST16 => (H5OPEN H5T_NATIVE_UINT_FAST16_g)
PRIiPTR=PRIiPTR => __PRIPTR_PREFIX "i"
SCNdFAST64=SCNdFAST64 => __PRI64_PREFIX "d"
SCNi8=SCNi8 => "hhi"
H5_HAVE_LIBM=H5_HAVE_LIBM => 1
__gid_t_defined=__gid_t_defined
INT64_MAX=INT64_MAX => (__INT64_C(9223372036854775807))
H5OPEN=H5OPEN => H5open(),
SCNoMAX=SCNoMAX => __PRI64_PREFIX "o"
H5_LT_OBJDIR=H5_LT_OBJDIR => ".libs/"
__GNU_LIBRARY__=__GNU_LIBRARY__ => 6
_BITS_BYTESWAP_H=_BITS_BYTESWAP_H => 1
H5_WANT_DCONV_EXCEPTION=H5_WANT_DCONV_EXCEPTION => 1
SCNoFAST8=SCNoFAST8 => "hho"
H5_CLEAR_MEMORY=H5_CLEAR_MEMORY => 1
H5_HAVE_STDLIB_H=H5_HAVE_STDLIB_H => 1
UINT_MAX=UINT_MAX => 4294967295U
__KEY_T_TYPE=__KEY_T_TYPE => __S32_TYPE
H5_HAVE_SYSTEM=H5_HAVE_SYSTEM => 1
PRIo64=PRIo64 => __PRI64_PREFIX "o"
H5T_UNIX_D64LE=H5T_UNIX_D64LE => (H5OPEN H5T_UNIX_D64LE_g)
_SVID_SOURCE=_SVID_SOURCE => 1
H5T_NATIVE_UCHAR=H5T_NATIVE_UCHAR => (H5OPEN H5T_NATIVE_UCHAR_g)
__FD_ISSET=__FD_ISSET(d, set) => ((__FDS_BITS (set)[__FDELT (d)] & __FDMASK (d)) != 0)
PRIu16=PRIu16 => "u"
H5_FCTESTDLL=H5_FCTESTDLL
SCHAR_MIN=SCHAR_MIN => (-128)
H5T_STD_B64BE=H5T_STD_B64BE => (H5OPEN H5T_STD_B64BE_g)
_H5ACpublic_H=_H5ACpublic_H
H5_ITER_CONT=H5_ITER_CONT => (0)
H5_HAVE_STDDEF_H=H5_HAVE_STDDEF_H => 1
H5T_INTEL_U8=H5T_INTEL_U8 => H5T_STD_U8LE
__bswap_constant_16=__bswap_constant_16(x) => ((unsigned short int) ((((x) >> 8) & 0xff) | (((x) & 0xff) << 8)))
UINT16_C=UINT16_C(c) => c
H5_NO_ALIGNMENT_RESTRICTIONS=H5_NO_ALIGNMENT_RESTRICTIONS => 1
SCNxLEAST8=SCNxLEAST8 => "hhx"
__BEGIN_NAMESPACE_C99=__BEGIN_NAMESPACE_C99
H5_SYSTEM_SCOPE_THREADS=H5_SYSTEM_SCOPE_THREADS => 1
PRIoFAST8=PRIoFAST8 => "o"
H5Topen_vers=H5Topen_vers => 1
_BITS_POSIX1_LIM_H=_BITS_POSIX1_LIM_H => 1
_POSIX_LINK_MAX=_POSIX_LINK_MAX => 8
H5T_STD_U16BE=H5T_STD_U16BE => (H5OPEN H5T_STD_U16BE_g)
DELAYTIMER_MAX=DELAYTIMER_MAX => 2147483647
__FSBLKCNT64_T_TYPE=__FSBLKCNT64_T_TYPE => __UQUAD_TYPE
_POSIX_SIGQUEUE_MAX=_POSIX_SIGQUEUE_MAX => 32
INT_FAST8_MIN=INT_FAST8_MIN => (-128)
__LDBL_REDIR_DECL=__LDBL_REDIR_DECL(name)
H5_SIZEOF_UINT16_T=H5_SIZEOF_UINT16_T => 2
USHRT_MAX=USHRT_MAX => 65535
LLONG_MAX=LLONG_MAX => 9223372036854775807LL
__SWBLK_T_TYPE=__SWBLK_T_TYPE => __SLONGWORD_TYPE
__pid_t_defined=__pid_t_defined
__END_DECLS=__END_DECLS
__OFF64_T_TYPE=__OFF64_T_TYPE => __SQUAD_TYPE
H5_LDOUBLE_TO_INTEGER_ACCURATE=H5_LDOUBLE_TO_INTEGER_ACCURATE => 1
__UQUAD_TYPE=__UQUAD_TYPE => __u_quad_t
H5F_ACC_CREAT=H5F_ACC_CREAT => (H5CHECK 0x0010u)
_M_I86=_M_I86 => 1
H5Aiterate_vers=H5Aiterate_vers => 1
H5Dcreate=H5Dcreate => H5Dcreate1
SCNd8=SCNd8 => "hhd"
__FSID_T_TYPE=__FSID_T_TYPE => struct { int __val[2]; }
__LDBL_REDIR1=__LDBL_REDIR1(name, proto, alias) => name proto
H5_WANT_DATA_ACCURACY=H5_WANT_DATA_ACCURACY => 1
H5_HAVE_SIGACTION=H5_HAVE_SIGACTION => 1
__FD_SET=__FD_SET(d, set) => ((void) (__FDS_BITS (set)[__FDELT (d)] |= __FDMASK (d)))
H5F_OBJ_LOCAL=H5F_OBJ_LOCAL => (0x0020u)
H5_HAVE_LONGJMP=H5_HAVE_LONGJMP => 1
H5_SIZEOF_INT_FAST64_T=H5_SIZEOF_INT_FAST64_T => 8
H5F_ACC_TRUNC=H5F_ACC_TRUNC => (H5CHECK 0x0002u)
__P=__P(args) => args
__need_time_t=__need_time_t
H5T_IEEE_F32BE=H5T_IEEE_F32BE => (H5OPEN H5T_IEEE_F32BE_g)
_POSIX_SEM_NSEMS_MAX=_POSIX_SEM_NSEMS_MAX => 256
__errordecl=__errordecl(name, msg) => extern void name (void)
__S16_TYPE=__S16_TYPE => short int
SCNuFAST8=SCNuFAST8 => "hhu"
__CONCAT=__CONCAT(x, y) => x ## y
PRIiFAST16=PRIiFAST16 => __PRIPTR_PREFIX "i"
H5T_VAX_F32=H5T_VAX_F32 => (H5OPEN H5T_VAX_F32_g)
__STDC_ISO_10646__=__STDC_ISO_10646__ => 200009L
__SIZEOF_PTHREAD_CONDATTR_T=__SIZEOF_PTHREAD_CONDATTR_T => 4
H5_HAVE_ATTRIBUTE=H5_HAVE_ATTRIBUTE => 1
H5_HAVE_GETPWUID=H5_HAVE_GETPWUID => 1
__int8_t_defined=__int8_t_defined
H5T_NATIVE_OPAQUE=H5T_NATIVE_OPAQUE => (H5OPEN H5T_NATIVE_OPAQUE_g)
H5_LDOUBLE_TO_INTEGER_WORKS=H5_LDOUBLE_TO_INTEGER_WORKS => 1
le16toh=le16toh(x) => (x)
HDF5_HL_F90CSTUBDLL=HDF5_HL_F90CSTUBDLL
H5_HAVE_GETHOSTNAME=H5_HAVE_GETHOSTNAME => 1
PRIiFAST32=PRIiFAST32 => __PRIPTR_PREFIX "i"
PRIo32=PRIo32 => "o"
__STRING=__STRING(x) => #x
H5_VSNPRINTF_WORKS=H5_VSNPRINTF_WORKS => 1
H5_SIZEOF_DOUBLE=H5_SIZEOF_DOUBLE => 8
H5check=H5check() => H5check_version(H5_VERS_MAJOR,H5_VERS_MINOR, H5_VERS_RELEASE)
H5Epush=H5Epush => H5Epush1
PRIdFAST64=PRIdFAST64 => __PRI64_PREFIX "d"
__FILE__=__FILE__
_POSIX_STREAM_MAX=_POSIX_STREAM_MAX => 8
_POSIX_NAME_MAX=_POSIX_NAME_MAX => 14
UINT_LEAST32_MAX=UINT_LEAST32_MAX => (4294967295U)
SCNi64=SCNi64 => __PRI64_PREFIX "i"
H5_HAVE_SRANDOM=H5_HAVE_SRANDOM => 1
PRId64=PRId64 => __PRI64_PREFIX "d"
__TIMER_T_TYPE=__TIMER_T_TYPE => void *
H5_HAVE_STRUCT_TIMEZONE=H5_HAVE_STRUCT_TIMEZONE => 1
__i386__=__i386__ => 1
__S64_TYPE=__S64_TYPE => __quad_t
H5_HAVE_FREXPF=H5_HAVE_FREXPF => 1
H5Tcommit_vers=H5Tcommit_vers => 1
_BITS_TYPES_H=_BITS_TYPES_H => 1
PATH_MAX=PATH_MAX => 4096
INT64_MIN=INT64_MIN => (-__INT64_C(9223372036854775807)-1)
__FD_CLR=__FD_CLR(d, set) => ((void) (__FDS_BITS (set)[__FDELT (d)] &= ~__FDMASK (d)))
PRIu32=PRIu32 => "u"
_H5Fpublic_H=_H5Fpublic_H
__FD_SETSIZE=__FD_SETSIZE => 1024
H5_HAVE_FREXPL=H5_HAVE_FREXPL => 1
__RLIM_T_TYPE=__RLIM_T_TYPE => __ULONGWORD_TYPE
__bswap_constant_32=__bswap_constant_32(x) => ((((x) & 0xff000000) >> 24) | (((x) & 0x00ff0000) >> 8) | (((x) & 0x0000ff00) << 8) | (((x) & 0x000000ff) << 24))
_POSIX_C_SOURCE=_POSIX_C_SOURCE => 200809L
PRIiLEAST8=PRIiLEAST8 => "i"
htole32=htole32(x) => (x)
__FSBLKCNT_T_TYPE=__FSBLKCNT_T_TYPE => __ULONGWORD_TYPE
__LITTLE_ENDIAN__=__LITTLE_ENDIAN__ => 1
H5_SIZEOF_INT_LEAST8_T=H5_SIZEOF_INT_LEAST8_T => 1
H5_SIZEOF_UINT_FAST16_T=H5_SIZEOF_UINT_FAST16_T => 4
H5T_VAX_F64=H5T_VAX_F64 => (H5OPEN H5T_VAX_F64_g)
__KERNEL_STRICT_NAMES=__KERNEL_STRICT_NAMES
SCNiPTR=SCNiPTR => __PRIPTR_PREFIX "i"
LLONG_MIN=LLONG_MIN => (-LLONG_MAX - 1LL)
htobe16=htobe16(x) => __bswap_16 (x)
_POSIX2_RE_DUP_MAX=_POSIX2_RE_DUP_MAX => 255
__USE_XOPEN2K=__USE_XOPEN2K => 1
H5Z_class_t=H5Z_class_t => H5Z_class1_t
H5_HAVE_STRDUP=H5_HAVE_STRDUP => 1
_POSIX2_BC_SCALE_MAX=_POSIX2_BC_SCALE_MAX => 99
PRIxLEAST32=PRIxLEAST32 => "x"
H5T_NATIVE_HSIZE=H5T_NATIVE_HSIZE => (H5OPEN H5T_NATIVE_HSIZE_g)
PRId32=PRId32 => "d"
INT_FAST64_MIN=INT_FAST64_MIN => (-__INT64_C(9223372036854775807)-1)
__need_size_t=__need_size_t
__GLIBC_MINOR__=__GLIBC_MINOR__ => 13
SCNuLEAST8=SCNuLEAST8 => "hhu"
WINT_MAX=WINT_MAX => (4294967295u)
INT_FAST8_MAX=INT_FAST8_MAX => (127)
__ULONGWORD_TYPE=__ULONGWORD_TYPE => unsigned long int
_POSIX_CHILD_MAX=_POSIX_CHILD_MAX => 25
H5T_STD_U8LE=H5T_STD_U8LE => (H5OPEN H5T_STD_U8LE_g)
__USING_NAMESPACE_C99=__USING_NAMESPACE_C99(name)
WCHAR_MIN=WCHAR_MIN => __WCHAR_MIN
SIZE_MAX=SIZE_MAX => (4294967295U)
H5T_STD_U32BE=H5T_STD_U32BE => (H5OPEN H5T_STD_U32BE_g)
PRIX16=PRIX16 => "X"
htole16=htole16(x) => (x)
COLL_WEIGHTS_MAX=COLL_WEIGHTS_MAX => 255
H5_VERS_MINOR=H5_VERS_MINOR => 8
H5Eprint=H5Eprint => H5Eprint1
PRIxFAST8=PRIxFAST8 => "x"
PRIxMAX=PRIxMAX => __PRI64_PREFIX "x"
__BEGIN_DECLS=__BEGIN_DECLS
HADDR_MAX=HADDR_MAX => (HADDR_UNDEF-1)
PRIu64=PRIu64 => __PRI64_PREFIX "u"
htobe32=htobe32(x) => __bswap_32 (x)
H5T_NATIVE_CHAR=H5T_NATIVE_CHAR => (CHAR_MIN?H5T_NATIVE_SCHAR:H5T_NATIVE_UCHAR)
H5T_NATIVE_LONG=H5T_NATIVE_LONG => (H5OPEN H5T_NATIVE_LONG_g)
H5_SIZEOF_FLOAT=H5_SIZEOF_FLOAT => 4
__id_t_defined=__id_t_defined
__nlink_t_defined=__nlink_t_defined
SHRT_MIN=SHRT_MIN => (-32768)
H5T_MIPS_B16=H5T_MIPS_B16 => H5T_STD_B16BE
BC_SCALE_MAX=BC_SCALE_MAX => _POSIX2_BC_SCALE_MAX
H5T_ALPHA_I32=H5T_ALPHA_I32 => H5T_STD_I32LE
SCNoPTR=SCNoPTR => __PRIPTR_PREFIX "o"
__OFF_T_TYPE=__OFF_T_TYPE => __SLONGWORD_TYPE
H5T_MIPS_I16=H5T_MIPS_I16 => H5T_STD_I16BE
__attribute_deprecated__=__attribute_deprecated__
H5_FC_FUNC_=H5_FC_FUNC_(name, NAME) => name ## _
PRIxLEAST16=PRIxLEAST16 => "x"
SCNiFAST64=SCNiFAST64 => __PRI64_PREFIX "i"
PIPE_BUF=PIPE_BUF => 4096
H5_ULLONG_TO_FP_CAST_WORKS=H5_ULLONG_TO_FP_CAST_WORKS => 1
_FEATURES_H=_FEATURES_H => 1
__extern_always_inline=__extern_always_inline => extern __always_inline
_POSIX_PATH_MAX=_POSIX_PATH_MAX => 256
H5_CONVERT_DENORMAL_FLOAT=H5_CONVERT_DENORMAL_FLOAT => 1
__RLIM64_T_TYPE=__RLIM64_T_TYPE => __UQUAD_TYPE
H5_PACKAGE_VERSION=H5_PACKAGE_VERSION => "1.8.4-patch1"
PRId16=PRId16 => "d"
PRIX32=PRIX32 => "X"
PRIuFAST8=PRIuFAST8 => "u"
H5T_NATIVE_USHORT=H5T_NATIVE_USHORT => (H5OPEN H5T_NATIVE_USHORT_g)
CHAR_BIT=CHAR_BIT => 8
PRIXLEAST8=PRIXLEAST8 => "X"
MQ_PRIO_MAX=MQ_PRIO_MAX => 32768
__USE_ATFILE=__USE_ATFILE => 1
H5T_MIPS_B32=H5T_MIPS_B32 => H5T_STD_B32BE
_STRUCT_TIMEVAL=_STRUCT_TIMEVAL => 1
minor=minor(dev) => gnu_dev_minor (dev)
H5T_INTEL_I8=H5T_INTEL_I8 => H5T_STD_I8LE
MB_LEN_MAX=MB_LEN_MAX => 16
H5_HAVE_FILTER_SCALEOFFSET=H5_HAVE_FILTER_SCALEOFFSET => 1
SCNuPTR=SCNuPTR => __PRIPTR_PREFIX "u"
H5_INCLUDE_HL=H5_INCLUDE_HL => 1
H5_SIZEOF_INT32_T=H5_SIZEOF_INT32_T => 4
__BIG_ENDIAN=__BIG_ENDIAN => 4321
H5T_ALPHA_I16=H5T_ALPHA_I16 => H5T_STD_I16LE
_PREDEFS_H=_PREDEFS_H
H5_HAVE_DLFCN_H=H5_HAVE_DLFCN_H => 1
__bos=__bos(ptr) => __builtin_object_size (ptr, __USE_FORTIFY_LEVEL > 1)
INT16_C=INT16_C(c) => c
H5_SIZEOF_UINT32_T=H5_SIZEOF_UINT32_T => 4
_POSIX2_BC_STRING_MAX=_POSIX2_BC_STRING_MAX => 1000
H5Pget_filter_vers=H5Pget_filter_vers => 1
htobe64=htobe64(x) => __bswap_64 (x)
__NLINK_T_TYPE=__NLINK_T_TYPE => __UWORD_TYPE
INT_MIN=INT_MIN => (-INT_MAX - 1)
PRIXPTR=PRIXPTR => __PRIPTR_PREFIX "X"
__LONG_LONG_PAIR=__LONG_LONG_PAIR(HI, LO) => LO, HI
__USE_POSIX199506=__USE_POSIX199506 => 1
UINTMAX_C=UINTMAX_C(c) => c ## ULL
H5T_VARIABLE=H5T_VARIABLE => ((size_t)(-1))
SCNoLEAST8=SCNoLEAST8 => "hho"
PRIxLEAST64=PRIxLEAST64 => __PRI64_PREFIX "x"
SCNx8=SCNx8 => "hhx"
H5_HAVE_SYS_RESOURCE_H=H5_HAVE_SYS_RESOURCE_H => 1
__daddr_t_defined=__daddr_t_defined
H5_HAVE_FEATURES_H=H5_HAVE_FEATURES_H => 1
H5Eclear_vers=H5Eclear_vers => 1
H5_SIZEOF_HSSIZE_T=H5_SIZEOF_HSSIZE_T => H5_SIZEOF_LONG_LONG
PRIuFAST16=PRIuFAST16 => __PRIPTR_PREFIX "u"
__restrict=__restrict
H5T_INTEL_U16=H5T_INTEL_U16 => H5T_STD_U16LE
H5T_STD_I32BE=H5T_STD_I32BE => (H5OPEN H5T_STD_I32BE_g)
H5_PACKAGE_URL=H5_PACKAGE_URL => ""
_POSIX_SEM_VALUE_MAX=_POSIX_SEM_VALUE_MAX => 32767
H5T_IEEE_F64BE=H5T_IEEE_F64BE => (H5OPEN H5T_IEEE_F64BE_g)
H5_HAVE_TIOCGETD=H5_HAVE_TIOCGETD => 1
HOST_NAME_MAX=HOST_NAME_MAX => 64
H5_HAVE_RANDOM=H5_HAVE_RANDOM => 1
INT_FAST64_MAX=INT_FAST64_MAX => (__INT64_C(9223372036854775807))
H5T_STD_B16LE=H5T_STD_B16LE => (H5OPEN H5T_STD_B16LE_g)
BYTE_ORDER=BYTE_ORDER => __BYTE_ORDER
__attribute_noinline__=__attribute_noinline__
H5T_NATIVE_INT_LEAST16=H5T_NATIVE_INT_LEAST16 => (H5OPEN H5T_NATIVE_INT_LEAST16_g)
__mode_t_defined=__mode_t_defined
H5Pget_filter_by_id_vers=H5Pget_filter_by_id_vers => 1
INT_LEAST64_MAX=INT_LEAST64_MAX => (__INT64_C(9223372036854775807))
H5_DLLCPP=H5_DLLCPP
H5_HAVE_SYS_TIMEB_H=H5_HAVE_SYS_TIMEB_H => 1
_LIBC_LIMITS_H_=_LIBC_LIMITS_H_ => 1
H5Ewalk=H5Ewalk => H5Ewalk1
__key_t_defined=__key_t_defined
SCNu64=SCNu64 => __PRI64_PREFIX "u"
__MODE_T_TYPE=__MODE_T_TYPE => __U32_TYPE
H5Gcreate_vers=H5Gcreate_vers => 1
H5T_NATIVE_INT_FAST32=H5T_NATIVE_INT_FAST32 => (H5OPEN H5T_NATIVE_INT_FAST32_g)
H5T_INTEL_U32=H5T_INTEL_U32 => H5T_STD_U32LE
__SWORD_TYPE=__SWORD_TYPE => int
SCNu32=SCNu32 => "u"
H5_SIZEOF_UNSIGNED=H5_SIZEOF_UNSIGNED => 4
INTMAX_MAX=INTMAX_MAX => (__INT64_C(9223372036854775807))
H5T_NATIVE_UINT_LEAST8=H5T_NATIVE_UINT_LEAST8 => (H5OPEN H5T_NATIVE_UINT_LEAST8_g)
H5T_OPAQUE_TAG_MAX=H5T_OPAQUE_TAG_MAX => 256
G_BYTE_ORDER=G_BYTE_ORDER => 1234
H5Pinsert_vers=H5Pinsert_vers => 1
CHARCLASS_NAME_MAX=CHARCLASS_NAME_MAX => 2048
WINT_MIN=WINT_MIN => (0u)
H5T_STD_U32LE=H5T_STD_U32LE => (H5OPEN H5T_STD_U32LE_g)
SCNxFAST16=SCNxFAST16 => __PRIPTR_PREFIX "x"
H5_USE_16_API_DEFAULT=H5_USE_16_API_DEFAULT => 1
UINT_LEAST8_MAX=UINT_LEAST8_MAX => (255)
WCHAR_MAX=WCHAR_MAX => __WCHAR_MAX
__DEV_T_TYPE=__DEV_T_TYPE => __UQUAD_TYPE
RE_DUP_MAX=RE_DUP_MAX => (0x7fff)
__uint32_t_defined=__uint32_t_defined
__BEGIN_NAMESPACE_STD=__BEGIN_NAMESPACE_STD
M_I86=M_I86 => 1
H5_ITER_ERROR=H5_ITER_ERROR => (-1)
H5_SIZEOF_INT_LEAST32_T=H5_SIZEOF_INT_LEAST32_T => 4
H5_PACKAGE_TARNAME=H5_PACKAGE_TARNAME => "hdf5"
H5T_MIPS_B64=H5T_MIPS_B64 => H5T_STD_B64BE
UINT_FAST32_MAX=UINT_FAST32_MAX => (4294967295U)
PRIdMAX=PRIdMAX => __PRI64_PREFIX "d"
__nonnull=__nonnull(params)
XATTR_LIST_MAX=XATTR_LIST_MAX => 65536
H5Dopen=H5Dopen => H5Dopen1
PRIiLEAST64=PRIiLEAST64 => __PRI64_PREFIX "i"
H5_SIZEOF_LONG=H5_SIZEOF_LONG => 4
H5T_INTEL_I64=H5T_INTEL_I64 => H5T_STD_I64LE
SCNu16=SCNu16 => "hu"
_SIGSET_H_types=_SIGSET_H_types => 1
SHRT_MAX=SHRT_MAX => 32767
H5T_NATIVE_HADDR=H5T_NATIVE_HADDR => (H5OPEN H5T_NATIVE_HADDR_g)
H5T_NATIVE_INT_FAST8=H5T_NATIVE_INT_FAST8 => (H5OPEN H5T_NATIVE_INT_FAST8_g)
H5_SIZEOF_INT_FAST16_T=H5_SIZEOF_INT_FAST16_T => 4
_BITS_POSIX2_LIM_H=_BITS_POSIX2_LIM_H => 1
LOGIN_NAME_MAX=LOGIN_NAME_MAX => 256
H5_HAVE_FSTAT64=H5_HAVE_FSTAT64 => 1
H5T_NATIVE_INT_FAST64=H5T_NATIVE_INT_FAST64 => (H5OPEN H5T_NATIVE_INT_FAST64_g)
_POSIX2_BC_BASE_MAX=_POSIX2_BC_BASE_MAX => 99
H5TEST_DLLVAR=H5TEST_DLLVAR => extern
H5Eget_auto_vers=H5Eget_auto_vers => 1
SCNxFAST32=SCNxFAST32 => __PRIPTR_PREFIX "x"
H5_HAVE_SIGNAL=H5_HAVE_SIGNAL => 1
H5_HLDLL=H5_HLDLL
H5Acreate_vers=H5Acreate_vers => 1
H5T_INTEL_B8=H5T_INTEL_B8 => H5T_STD_B8LE
H5_FCTESTDLLVAR=H5_FCTESTDLLVAR => extern
H5Gopen=H5Gopen => H5Gopen1
H5_LDOUBLE_TO_LLONG_ACCURATE=H5_LDOUBLE_TO_LLONG_ACCURATE => 1
INT32_MAX=INT32_MAX => (2147483647)
__ino_t_defined=__ino_t_defined
H5_HAVE_TMPFILE=H5_HAVE_TMPFILE => 1
SCNu8=SCNu8 => "hhu"
PRIuLEAST64=PRIuLEAST64 => __PRI64_PREFIX "u"
_LIMITS_H=_LIMITS_H => 1
H5T_MIPS_I32=H5T_MIPS_I32 => H5T_STD_I32BE
le32toh=le32toh(x) => (x)
SSIZE_MAX=SSIZE_MAX => LONG_MAX
H5T_STD_B32BE=H5T_STD_B32BE => (H5OPEN H5T_STD_B32BE_g)
PRIX64=PRIX64 => __PRI64_PREFIX "X"
SCNiLEAST8=SCNiLEAST8 => "hhi"
__FLOAT_WORD_ORDER=__FLOAT_WORD_ORDER => __BYTE_ORDER
_SYS_CDEFS_H=_SYS_CDEFS_H => 1
_SYS_SYSMACROS_H=_SYS_SYSMACROS_H => 1
H5T_STD_I32LE=H5T_STD_I32LE => (H5OPEN H5T_STD_I32LE_g)
H5_VERS_SUBRELEASE=H5_VERS_SUBRELEASE => "patch1"
__STDC__=__STDC__ => 1
PRIiLEAST16=PRIiLEAST16 => "i"
__NFDBITS=__NFDBITS => (8 * (int) sizeof (__fd_mask))
INT_LEAST16_MAX=INT_LEAST16_MAX => (32767)
H5_SIZEOF_UINT64_T=H5_SIZEOF_UINT64_T => 8
H5T_INTEL_U64=H5T_INTEL_U64 => H5T_STD_U64LE
PRIdPTR=PRIdPTR => __PRIPTR_PREFIX "d"
BC_STRING_MAX=BC_STRING_MAX => _POSIX2_BC_STRING_MAX
____gwchar_t_defined=____gwchar_t_defined => 1
H5I_INVALID_HID=H5I_INVALID_HID => (-1)
H5T_NATIVE_FLOAT=H5T_NATIVE_FLOAT => (H5OPEN H5T_NATIVE_FLOAT_g)
H5F_ACC_DEFAULT=H5F_ACC_DEFAULT => (H5CHECK 0xffffu)
H5_FC_FUNC=H5_FC_FUNC(name, NAME) => name ## _
_H5version_H=_H5version_H
SCNo8=SCNo8 => "hho"
INT_MAX=INT_MAX => 2147483647
htole64=htole64(x) => (x)
UINT64_C=UINT64_C(c) => c ## ULL
H5_SIZEOF_UINT_FAST32_T=H5_SIZEOF_UINT_FAST32_T => 4
H5_HAVE_FTELLO=H5_HAVE_FTELLO => 1
NFDBITS=NFDBITS => __NFDBITS
H5_HAVE_SETJMP_H=H5_HAVE_SETJMP_H => 1
SCNxFAST64=SCNxFAST64 => __PRI64_PREFIX "x"
__ptrvalue=__ptrvalue
__END_NAMESPACE_STD=__END_NAMESPACE_STD
H5_HAVE_LIBPTHREAD=H5_HAVE_LIBPTHREAD => 1
H5_HAVE_DIFFTIME=H5_HAVE_DIFFTIME => 1
H5T_MIPS_I64=H5T_MIPS_I64 => H5T_STD_I64BE
H5_FCDLL=H5_FCDLL
__u_char_defined=__u_char_defined
H5_LLONG_TO_FP_CAST_WORKS=H5_LLONG_TO_FP_CAST_WORKS => 1
_POSIX_MQ_PRIO_MAX=_POSIX_MQ_PRIO_MAX => 32
H5Pinsert=H5Pinsert => H5Pinsert1
PRIX8=PRIX8 => "X"
H5Eset_auto_vers=H5Eset_auto_vers => 1
H5_USE_16_API=H5_USE_16_API => 1
H5_HAVE_TIOCGWINSZ=H5_HAVE_TIOCGWINSZ => 1
PRIoLEAST8=PRIoLEAST8 => "o"
PRIiLEAST32=PRIiLEAST32 => "i"
H5T_INTEL_I32=H5T_INTEL_I32 => H5T_STD_I32LE
PRIiFAST8=PRIiFAST8 => "i"
__need_clockid_t=__need_clockid_t
_POSIX_SSIZE_MAX=_POSIX_SSIZE_MAX => 32767
_POSIX2_BC_DIM_MAX=_POSIX2_BC_DIM_MAX => 2048
H5T_ALPHA_I64=H5T_ALPHA_I64 => H5T_STD_I64LE
H5AC__MAX_TRACE_FILE_NAME_LEN=H5AC__MAX_TRACE_FILE_NAME_LEN => 1024
__SUSECONDS_T_TYPE=__SUSECONDS_T_TYPE => __SLONGWORD_TYPE
H5_HAVE_SIGLONGJMP=H5_HAVE_SIGLONGJMP => 1
H5E_error_t=H5E_error_t => H5E_error1_t
